### ISSUE TITLE
Issues with 9.5.0 build

### ISSUE THREAD

**Issue by amalagaura** [GeographicaGS/Docker-PostGIS#2]
Thanks for these containers. They are very helpful.

I had a few issues trying to upgrade to the new 9.5.0 build scripts.
1. Restarting the container I sometimes get invalid locale errors. On checking it is because there is no `local-gen en-US.utf-8`. In the 9.4.5 this is done at compile time as the locale is fixed? In the 9.5.0 it is done on creating the new data directory. This doesn't make sense because it needs to be persisted in the container so it either needs to be done on run.sh (container start) or in compile.sh (container build). Not on initdb as it is now.
2. I was having permission errors that the mounted /data directory is not owned by postgres. This is another difference with 9.4.5 where the following is in run.sh. It is not in the 9.5.0 run.sh

```
chown postgres:postgres ${POSTGRES_DATA_FOLDER}
chmod 700 ${POSTGRES_DATA_FOLDER}
echo "postgres:${POSTGRES_PASSWD}" | chpasswd -e
```

**Comment by malkab** [comment]
Lots of thanks for dropping by and commenting. Seems that we haven't tested enough beyond our local locale! I'll patch ASAP to fix this shortcomings.

**Comment by amalagaura** [comment]
Thanks for that. The containers really are useful for postgis.

I am also only using en-US.UTF-8 but it is not included by default and needs the locale-gen. 

One more thing, I had an issue one time with the gosu installation. I saw you are using 1.2, I changed it to 1.7. It was probably just a network issue, but might as well upgrade to 1.7 as well.

**Comment by amalagaura** [comment]
Also just a heads up, I had weird bugs with Postgres 9.5.0 where it would not use function indexes. I upgraded to 9.5.2 with your image and the latest PostGIS but did not include the patches and it worked fine.
