### ISSUE TITLE
Nimble-Newt startup error

### ISSUE THREAD

**Issue by zephyrthenoble** [GeographicaGS/Docker-PostGIS#34]
When starting Nimble-Newt, using the recommended command `docker run -d -P --name pgcontainer geographica/postgis:nimble_newt`, the container dies immediately.  Looking at the logs, I got the error `/usr/local/bin/run.sh: line 12: locale-gen: command not found`.  

Adding the line `RUN apt-get update && apt-get install locale` in the Dockerfile fixed this error.

**Comment by cayetanobv** [comment]
Hi @zephyrthenoble ,

Thanks for report this bug. I've added this line in Dockerfile and merged with master (and it works well). Docker Hub images for Nimble Newt are re-building now with this fix.

Thanks again!
