### ISSUE TITLE
Postgis 3 with GDAL + Raster support

### ISSUE THREAD

**Issue by Rovaro** [GeographicaGS/Docker-PostGIS#61]
Are there any plans of adding a tag for postgis 3 with the raster extension installed?

The GDAL/raster support was removed from Dev version in https://github.com/GeographicaGS/Docker-PostGIS/issues/54.

**Comment by ccabanero** [comment]
Just chiming in that I am interested in this too.  Below is what I see in Terminal after connecting to the database and attempting to enable __postgis_raster__:

When executing the following:

````
CREATE EXTENSION postgis_raster;
````

I receive the following:

````
ERROR:  could not open extension control file "/usr/local/share/postgresql/extension/postgis_raster.control": No such file or directory
Time: 0.798 ms
````

**Comment by cayetanobv** [comment]
@ccabanero last release of Docker image does not support raster but we are going to prepare a new alternative release with GDAL to support it again.

**Comment by Rovaro** [comment]
A released was created containing raster support: [Unbiased_Uakari_raster](https://github.com/GeographicaGS/Docker-PostGIS/tree/master/Unbiased_Uakari_raster).

Closing this ticket.
