### ISSUE TITLE
Extension missing

### ISSUE THREAD

**Issue by toton6868** [GeographicaGS/Docker-PostGIS#70]
`hstore` extension was not found.

```
ERROR:  could not open extension control file "/usr/local/share/postgresql/extension/hstore.control": No such file or directory
```

**Comment by toton6868** [comment]
I think cleaning up all the extension is not a wise decision

**Comment by cayetanobv** [comment]
Hi @toton6868 ,

This extension (`hstore`) is in Appendix F of PostgreSQL with another 45 additional modules. Most of these modules are not used in a common use case so we think is better not include all of them to reduce image size. A small image size is important when you use this image in CI environment. If you need to add some Appendix F module, like `hstore`, it's very easy including compilation script in `packages/compile.sh` file.

Thanks to use this Docker image.

**Comment by toton6868** [comment]
I have solved this with the following changes in the `compile.sh` file by adding 3 lines after Postgresql compilation
```
# Compilation of PostgreSQL
cd src/postgresql-${PG_VERSION}
    ./configure --prefix=/usr/local --with-pgport=5432 --with-python --with-openssl --with-libxml --with-libxslt --with-zlib --with-llvm
    make -j "$(nproc)"
    make install
    make all
    make install
cd contrib/hstore
    make
    make install
cd ../../../..
ldconfig
```
